// Maths schemes of work (week-by-week plans), shared by the student dashboard and the
// staff Lesson Mapping page. Each lesson slot has an id like 'Y10-T1-W1-L3'
// (plan, term, week, lesson). Which walkthrough questions belong to each slot is chosen
// by the maths department on lesson-mapping.html and stored in Supabase
// (lesson_slot_questions); MATHS_PLAN_SUGGESTIONS below only pre-filled that.
window.MATHS_PLANS = {
  Y10: {
    label: 'Year 10', year: 10, live: true,
    terms: [
      {
        term: 'Term 1 — Foundations',
        sub: "Units 1–3: Introduction to mathematics I & II; Further algebra, Pythagoras' theorem, surds and appropriate accuracy",
        weeks: [
          ['Types of number', 'Types of number', 'The four operations', 'Indices I'],
          ['Powers and roots', 'Time', 'Introduction to algebra', 'Algebraic manipulation'],
          ['Algebraic manipulation', 'Classifying statistical data', 'Geometrical constructions', 'Money'],
          ['Units of measure', 'Fractions, decimals and percentages', 'Fractions, decimals and percentages', 'Percentages'],
          ['Percentages', 'Exponential growth and decay', 'Interpreting statistical data', 'Interpreting statistical data'],
          ['Averages and range', 'Averages and range', 'Statistical charts and diagrams', 'Statistical charts and diagrams'],
          ['Area and perimeter', 'Geometrical terms', 'Ordering', 'Estimation'],
          ['Algebraic fractions', 'Algebraic fractions', 'Equations (linear, simultaneous, quadratic)', 'Equations (linear, simultaneous, quadratic)'],
          ['Equations (linear, simultaneous, quadratic)', 'Equations (linear, simultaneous, quadratic)', 'Proportion', 'Surds'],
          ['Surds', "Pythagoras' theorem", "Pythagoras' theorem", 'Term 1 review / consolidation'],
        ],
      },
      {
        term: 'Term 2 — Geometry & Data',
        sub: 'Units 4–6: Coordinate geometry I, ratio and scale drawing; Probability I, geometry and graphs; Circles, 3D mensuration, vectors and cumulative frequency',
        weeks: [
          ['Coordinates', 'Drawing linear graphs', 'Drawing linear graphs', 'Gradient of linear graphs'],
          ['Gradient of linear graphs', 'Length and midpoint', 'Equations of linear graphs', 'Equations of linear graphs'],
          ['Ratio and proportion', 'Ratio and proportion', 'Rates', 'Scale drawings'],
          ['Scale drawings', 'Introduction to probability', 'Relative and expected frequencies', 'Symmetry'],
          ['Angles', 'Angles', 'Circle theorems I', 'Circle theorems I'],
          ['Graphs in practical situations', 'Graphs in practical situations', 'Graphs of functions', 'Graphs of functions'],
          ['Sketching curves', 'Sketching curves', 'Circles, arcs and sectors', 'Indices II'],
          ['Surface area and volume', 'Surface area and volume', 'Compound shapes and solids', 'Transformations'],
          ['Transformations', 'Vectors in two dimensions', 'Inequalities', 'Inequalities'],
          ['Cumulative frequency diagrams', 'Cumulative frequency diagrams', 'Term 2 review / consolidation', ''],
        ],
      },
      {
        term: 'Term 3 — Trigonometry, Similarity & Sets',
        sub: 'Units 7–9: Standard form, similarity, trigonometry I and probability II; Coordinate geometry II, accuracy and trigonometry II; Sets, scatter diagrams, 3D trig and vector geometry',
        weeks: [
          ['Standard form', 'Similarity', 'Right-angled triangles', 'Right-angled triangles'],
          ['Right-angled triangles', 'Exact trigonometric values', 'Trigonometric functions', 'Trigonometric functions'],
          ['Probability of combined events', 'Probability of combined events', 'Sequences', 'Sequences'],
          ['Sequences', 'Circle theorems II', 'Circle theorems II', 'Circle theorems II'],
          ['Parallel lines', 'Perpendicular lines', 'Perpendicular lines', 'Limits of accuracy'],
          ['Limits of accuracy', 'Limits of accuracy', 'Limits of accuracy', 'Non-right-angled triangles (sine/cosine rule)'],
          ['Non-right-angled triangles (sine/cosine rule)', 'Non-right-angled triangles (sine/cosine rule)', 'Sets', 'Sets'],
          ['Scatter diagrams', 'Scatter diagrams', "Pythagoras' theorem and trigonometry in 3D", "Pythagoras' theorem and trigonometry in 3D"],
          ['Magnitude of a vector', 'Vector geometry', 'Vector geometry', 'Vector geometry'],
          ['Review / mock exam preparation', 'Review / mock exam preparation', 'Review / mock exam preparation', 'Review / mock exam preparation'],
        ],
      },
      {
        term: 'Term 4 — Functions & Revision',
        sub: 'Unit 10: Functions, histograms (& differentiation); full-syllabus revision; past paper practice and mock exams',
        weeks: [
          ['Functions', 'Functions', 'Functions', 'Histograms'],
          ['Histograms', 'Histograms', 'Differentiation', 'Differentiation'],
          ['Differentiation', 'Differentiation', 'Revision: Number & algebra (Units 1-3)', 'Revision: Number & algebra (Units 1-3)'],
          ['Revision: Number & algebra (Units 1-3)', 'Revision: Number & algebra (Units 1-3)', 'Revision: Number & algebra (Units 1-3)', 'Revision: Number & algebra (Units 1-3)'],
          ['Revision: Coordinate geometry, probability, geometry (Units 4-6)', 'Revision: Coordinate geometry, probability, geometry (Units 4-6)', 'Revision: Coordinate geometry, probability, geometry (Units 4-6)', 'Revision: Coordinate geometry, probability, geometry (Units 4-6)'],
          ['Revision: Coordinate geometry, probability, geometry (Units 4-6)', 'Revision: Coordinate geometry, probability, geometry (Units 4-6)', 'Revision: Trigonometry, similarity, accuracy (Units 7-8)', 'Revision: Trigonometry, similarity, accuracy (Units 7-8)'],
          ['Revision: Trigonometry, similarity, accuracy (Units 7-8)', 'Revision: Trigonometry, similarity, accuracy (Units 7-8)', 'Revision: Sets, vectors, functions, calculus (Units 9-10)', 'Revision: Sets, vectors, functions, calculus (Units 9-10)'],
          ['Revision: Sets, vectors, functions, calculus (Units 9-10)', 'Revision: Sets, vectors, functions, calculus (Units 9-10)', 'Past paper practice / mock exam', 'Past paper practice / mock exam'],
          ['Past paper practice / mock exam', 'Past paper practice / mock exam', 'Past paper practice / mock exam', 'Past paper practice / mock exam'],
          ['Past paper practice / mock exam', 'Past paper practice / mock exam', 'Past paper practice / mock exam', 'Past paper practice / mock exam'],
        ],
      },
    ],
  },
  Y11: {
    label: 'Year 11', year: 11, live: false, // not shown to students yet
    terms: [
      {
        term: 'Term 1',
        sub: 'Units 7–10: Trigonometry (right-angled, exact values, graphs, non-right-angled, 3D); Transformations and vectors; Probability; Statistics',
        weeks: [
          ["Pythagoras' theorem", 'Right-angled triangles (sin/cos/tan ratios)', 'Right-angled triangles (solving sides & angles)', 'Right-angled triangles (elevation/depression, bearings, perpendicular distance)'],
          ['Exact trigonometric values', 'Trigonometric functions (sketching sin/cos/tan graphs)', 'Trigonometric functions (solving equations)', 'Non-right-angled triangles (sine rule)'],
          ['Non-right-angled triangles (cosine rule)', 'Non-right-angled triangles (area of triangle, ambiguous case)', "Pythagoras' theorem & trigonometry in 3D", "Pythagoras' theorem & trigonometry in 3D (angle between line and plane)"],
          ['Transformations (reflection, rotation)', 'Transformations (enlargement, translation, combinations)', 'Vectors in two dimensions (notation, addition/subtraction)', 'Vectors in two dimensions (multiplying by a scalar)'],
          ['Magnitude of a vector', 'Vector geometry (position vectors)', 'Vector geometry (sum/difference, parallel vectors)', 'Vector geometry (ratio, collinearity, proof-style problems)'],
          ['Introduction to probability (scale, notation, single events)', 'Introduction to probability (complement, Venn diagrams)', 'Relative and expected frequencies (relative frequency)', 'Relative and expected frequencies (expected frequency; fair, bias, random)'],
          ['Probability of combined events (sample space diagrams)', 'Probability of combined events (tree diagrams, with/without replacement)', 'Probability of combined events (Venn diagrams)', 'Conditional probability'],
          ['Classifying statistical data', 'Interpreting statistical data', 'Averages and measures of spread (mean, median, mode, range)', 'Averages and measures of spread (quartiles, IQR, estimated mean for grouped data)'],
          ['Statistical charts and diagrams (bar, pie, pictogram, stem-and-leaf)', 'Scatter diagrams', 'Cumulative frequency diagrams', 'Histograms'],
          ['Review: Trigonometry', 'Review: Transformations and vectors', 'Review: Probability', 'Review: Statistics'],
        ],
      },
    ],
  },
};

window.mathsSlotId = function (planKey, t, w, l) { return planKey + '-T' + (t + 1) + '-W' + (w + 1) + '-L' + (l + 1); };

// Starting suggestions used to pre-fill the mapping (file#question, or file alone for a whole walkthrough).
// Keyed by lesson name, so a lesson that repeats across weeks starts with the same list.
(function () {
  var n10 = 'year10/number-y10.html', a10 = 'year10/algebra-y10.html', s10 = 'year10/stats-y10.html',
    m10 = 'year10/mensuration-y10.html', g10 = 'year10/geometry-y10.html', gr10 = 'year10/graphs-y10.html',
    t10 = 'year10/trig-y10.html', ed10 = 'year10/elevation-depression-y10.html', ct10 = 'year10/circle-theorems-y10.html',
    sim10 = 'year10/similarity-y10.html', su10 = 'year10/surds-y10.html', pr10 = 'year10/proportion-y10.html',
    rd10 = 'year10/recurring-decimals-y10.html', cd10 = 'year10/calculus-diff-y10.html', con10 = 'year10/constructions-y10.html',
    al11 = 'year11/algebra-y11.html', tg11 = 'year11/trig-graphs-y11.html', v11 = 'year11/vectors-y11.html',
    tr11 = 'year11/transformations-y11.html', tra11 = 'year11/transformations-adv-y11.html', pa11 = 'year11/probability-adv-y11.html',
    sets11 = 'year11/sets-y11.html', h11 = 'year11/histograms-y11.html', me11 = 'year11/mensuration-y11.html',
    ge11 = 'year11/geometry-y11.html', sq11 = 'year11/sequences-adv-y11.html', in11 = 'year11/inequalities-y11.html',
    pc11 = 'year11/percentages-y11.html', ex11 = 'year11/exponential-y11.html';
  function q(file) { return Array.prototype.slice.call(arguments, 1).map(function (n) { return file + '#' + n; }); }
  function all() { return [].concat.apply([], arguments); }
  var S = {
    // Year 10 Term 1
    'Types of number': all(['bridge_mth_y10/BRG10-MTH-01.html'], q(n10, 1, 2), q('year07/sequences-y7.html', 4)),
    'The four operations': all(q(n10, 12), q('year08/mixed-operations-y8.html', 1, 6, 9), q('year07/negative-numbers-y7.html', 4, 5),
      q('year08/fractions-percentages-ratio-y8.html', 1, 2), q('year08/division-y8.html', 4, 7, 9), q('year08/addition-subtraction-y8.html', 5)),
    'Indices I': q(n10, 3, 11),
    'Powers and roots': all(q(n10, 3), q('year07/squares-cubes-roots-y7.html', 6, 9)),
    'Time': all(['bridge_mth_y10/BRG10-MTH-05.html'], q('year08/units-measurement-y8.html', 7)),
    'Introduction to algebra': all(q('year07/algebra-y7.html', 1, 2, 3), q('year07/substitution-y7.html', 1)),
    'Algebraic manipulation': all(q(a10, 2, 3, 9), q('year08/difference-of-squares-y8.html', 1), q(al11, 2)),
    'Geometrical constructions': q(con10, 1, 2, 3, 4),
    'Money': all(q('year07/percentages-y7.html', 8), q(pc11, 4), ['bridge_mth_y9/BRG9-MTH-02.html']),
    'Units of measure': all(q('year08/units-measurement-y8.html', 1, 6), q('year08/perimeter-area-volume-y8.html', 10)),
    'Fractions, decimals and percentages': all(q(n10, 5), q(rd10, 2, 4, 5, 9, 10)),
    'Percentages': all(q(n10, 6, 7), q(pc11, 1, 2, 3, 5)),
    'Exponential growth and decay': q(ex11, 1, 3, 4, 7, 9),
    'Interpreting statistical data': all(q(s10, 6, 7), q('year07/comparing-data-sets-y7.html', 1, 6), q('year08/data-handling-y8.html', 9)),
    'Averages and range': q(s10, 1, 2, 3),
    'Statistical charts and diagrams': all(q(s10, 4, 5), q(rd10, 6), q('year07/stem-leaf-y7.html', 7)),
    'Area and perimeter': all(q(m10, 1, 2), q('year08/perimeter-area-volume-y8.html', 1, 9)),
    'Geometrical terms': all(q('year08/shapes-construction-y8.html', 6, 7), ['bridge_mth/BRG-MTH-08.html']),
    'Ordering': all(q('year07/ordering-integers-y7.html', 4, 5), q('year08/place-value-rounding-y8.html', 9)),
    'Estimation': all(q('year08/place-value-rounding-y8.html', 2, 3, 4), q('year07/standard-form-estimation-y7.html', 5)),
    'Algebraic fractions': q(a10, 7),
    'Equations (linear, simultaneous, quadratic)': all(q(a10, 1, 4, 6, 9, 10), q(al11, 1, 2, 3)),
    'Proportion': q(pr10, 1, 2, 4, 5, 7),
    'Surds': q(su10, 1, 2, 3, 4, 5, 6, 7, 8),
    "Pythagoras' theorem": all(q('year09/pythagoras-trig-y9.html', 1, 2, 3), q(t10, 1, 4)),
    'Term 1 review / consolidation': ['year10/misconceptions-y10.html'],
    // Year 10 Term 2
    'Coordinates': q('year07/coordinates-y7.html', 1, 2),
    'Drawing linear graphs': all(q('year08/drawing-straight-line-graphs-y8.html', 1, 2), q(gr10, 1)),
    'Gradient of linear graphs': all(q('year08/gradient-y-intercept-y8.html', 1, 2), q('year09/graphs-y9.html', 4)),
    'Length and midpoint': all(q('addmaths/straight-lines-addmaths.html', 5), q('year07/coordinates-y7.html', 8)),
    'Equations of linear graphs': all(q('year09/graphs-y9.html', 4, 5, 6), q('year08/gradient-y-intercept-y8.html', 3)),
    'Ratio and proportion': all(q(n10, 8, 10), q('year07/ratio-y7.html', 3), ['ext_mth/EXT-MTH-04.html']),
    'Rates': all(['year09/rates-speed-density-y9.html'], q('year08/units-measurement-y8.html', 2, 4, 5)),
    'Scale drawings': all(q('year08/units-measurement-y8.html', 3, 10), q(g10, 10), q('year07/constructions-y7.html', 10)),
    'Introduction to probability': all(q(s10, 8), q('year07/probability-y7.html', 1)),
    'Relative and expected frequencies': all(q('year07/probability-y7.html', 4, 5), q('year08/probability-y8.html', 2, 7), q('year09/probability-y9.html', 8)),
    'Symmetry': q(g10, 7, 8, 9),
    'Angles': q(g10, 1, 2, 3, 4, 5, 6),
    'Circle theorems I': q(ct10, 1, 2, 3, 4, 5, 7),
    'Graphs in practical situations': q(gr10, 3, 4, 7),
    'Graphs of functions': q(gr10, 2, 5, 6, 8, 9),
    'Sketching curves': q(gr10, 2, 5, 6, 9),
    'Circles, arcs and sectors': all(q(m10, 6), q(me11, 7, 14)),
    'Surface area and volume': all(q(m10, 3, 4, 5, 7, 8), q(me11, 1, 2, 3, 4, 5, 6)),
    'Compound shapes and solids': all(q(me11, 9, 11, 12, 13, 15), q(m10, 2)),
    'Transformations': all(q(tr11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10), q(tra11, 1, 4, 8)),
    'Vectors in two dimensions': q(v11, 1, 2, 3, 5),
    'Inequalities': q(in11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
    'Cumulative frequency diagrams': all(q(s10, 7), q('year09/statistics-y9.html', 3, 6)),
    'Term 2 review / consolidation': ['year10/misconceptions-y10.html'],
    // Year 10 Term 3
    'Standard form': all(q(n10, 4), q('year09/number-y9.html', 4, 5)),
    'Similarity': q(sim10, 1, 2, 3, 5, 7),
    'Right-angled triangles': all(q(t10, 2, 3, 4, 5), q(ed10, 1, 2, 3, 8)),
    'Exact trigonometric values': q(tg11, 4),
    'Trigonometric functions': q(tg11, 1, 2, 3, 5, 6, 8),
    'Probability of combined events': all(q(s10, 9, 10), q(pa11, 1, 5, 6, 10)),
    'Sequences': all(q(sq11, 1, 2, 3, 4, 7), q(al11, 7)),
    'Circle theorems II': all(q(ct10, 6, 8, 9, 10), q(ge11, 7, 8, 9)),
    'Parallel lines': all(q('addmaths/straight-lines-addmaths.html', 3), q('year09/graphs-y9.html', 7)),
    'Perpendicular lines': q('addmaths/straight-lines-addmaths.html', 4, 7),
    'Limits of accuracy': q(n10, 9),
    'Non-right-angled triangles (sine/cosine rule)': q(t10, 6, 7, 8, 9, 10),
    'Sets': q(sets11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
    'Scatter diagrams': all(q(s10, 6), q('year09/statistics-y9.html', 1, 5)),
    "Pythagoras' theorem and trigonometry in 3D": all(q(ge11, 10), q('addmaths/trigonometry-addmaths.html', 8)),
    'Magnitude of a vector': q(v11, 4, 10),
    'Vector geometry': q(v11, 6, 7, 8, 9),
    'Review / mock exam preparation': ['year10/eoy-aoc-y10.html', 'year10/misconceptions-y10.html'],
    // Year 10 Term 4
    'Functions': all(q(al11, 4, 5, 6), q('addmaths/functions-addmaths.html', 1, 2, 3, 4)),
    'Histograms': q(h11, 1, 2, 3, 4, 7),
    'Differentiation': q(cd10, 1, 2, 3, 4),
    'Revision: Number & algebra (Units 1-3)': [n10, a10, su10, pr10],
    'Revision: Coordinate geometry, probability, geometry (Units 4-6)': [gr10, g10, ct10, m10, me11, tr11],
    'Revision: Trigonometry, similarity, accuracy (Units 7-8)': all([t10, sim10, ed10, tg11], q(n10, 9)),
    'Revision: Sets, vectors, functions, calculus (Units 9-10)': all([sets11, v11, cd10, h11], q(al11, 4, 5, 6)),
    'Past paper practice / mock exam': ['year10/eoy-aoc-y10.html'],
    // Year 11 Term 1
    'Right-angled triangles (sin/cos/tan ratios)': q(t10, 2, 3),
    'Right-angled triangles (solving sides & angles)': q(t10, 2, 3, 4),
    'Right-angled triangles (elevation/depression, bearings, perpendicular distance)': all(q(ed10, 1, 2, 9, 10), q(t10, 5)),
    'Trigonometric functions (sketching sin/cos/tan graphs)': q(tg11, 1, 2, 3, 10),
    'Trigonometric functions (solving equations)': q(tg11, 5, 6, 7, 8, 9),
    'Non-right-angled triangles (sine rule)': q(t10, 6, 7),
    'Non-right-angled triangles (cosine rule)': q(t10, 8, 9),
    'Non-right-angled triangles (area of triangle, ambiguous case)': q(t10, 10),
    "Pythagoras' theorem & trigonometry in 3D": q(ge11, 10),
    "Pythagoras' theorem & trigonometry in 3D (angle between line and plane)": q('addmaths/trigonometry-addmaths.html', 8),
    'Transformations (reflection, rotation)': q(tr11, 2, 3, 4, 5, 6),
    'Transformations (enlargement, translation, combinations)': all(q(tr11, 1, 7, 8, 9), q(tra11, 4, 5, 8)),
    'Vectors in two dimensions (notation, addition/subtraction)': q(v11, 1, 2, 5),
    'Vectors in two dimensions (multiplying by a scalar)': q(v11, 3),
    'Vector geometry (position vectors)': q(v11, 6, 8),
    'Vector geometry (sum/difference, parallel vectors)': q(v11, 7, 9),
    'Introduction to probability (scale, notation, single events)': all(q('year07/probability-y7.html', 1), q(s10, 8)),
    'Introduction to probability (complement, Venn diagrams)': all(q(pa11, 6), q(sets11, 10)),
    'Relative and expected frequencies (relative frequency)': all(q('year07/probability-y7.html', 4, 5), q('year08/probability-y8.html', 2)),
    'Relative and expected frequencies (expected frequency; fair, bias, random)': all(q('year08/probability-y8.html', 7), q('year09/probability-y9.html', 8)),
    'Probability of combined events (sample space diagrams)': q(s10, 9),
    'Probability of combined events (tree diagrams, with/without replacement)': all(q(s10, 10), q(pa11, 1, 5)),
    'Probability of combined events (Venn diagrams)': all(q(sets11, 10), q(pa11, 4)),
    'Conditional probability': q(pa11, 2, 3, 4, 7, 8),
    'Averages and measures of spread (mean, median, mode, range)': q(s10, 1, 2),
    'Averages and measures of spread (quartiles, IQR, estimated mean for grouped data)': all(q(s10, 3, 7), q(rd10, 7), q(h11, 8)),
    'Statistical charts and diagrams (bar, pie, pictogram, stem-and-leaf)': all(q(s10, 4, 5), q(rd10, 6), q('year07/stem-leaf-y7.html', 1)),
    'Review: Trigonometry': [t10, tg11, ed10],
    'Review: Transformations and vectors': [tr11, v11],
    'Review: Probability': all([pa11], q(s10, 8, 9, 10)),
    'Review: Statistics': [s10, h11, 'year11/misconceptions-y11.html'],
  };
  window.MATHS_PLAN_SUGGESTIONS = S;
})();

// Lessons the syllabus audit found without suitable IGCSE Extended content (pre-fills "needs content")
window.MATHS_PLAN_GAPS = {
  'Types of number': 'No reciprocals, triangular numbers only at Y8, natural numbers never defined.',
  'The four operations': 'Four rules with fractions and decimals only at Y7/Y8 level.',
  'Introduction to algebra': 'Only Y7–Y9 walkthroughs.',
  'Algebraic manipulation': 'No expanding three brackets, factorising by grouping, or ax³+bx²+cx.',
  'Classifying statistical data': 'Nothing exists: discrete/continuous, qualitative/quantitative.',
  'Money': 'No dedicated walkthrough; only one currency-conversion question.',
  'Interpreting statistical data': 'Nothing at Y10; nothing on the limits of conclusions.',
  'Statistical charts and diagrams': 'No composite or dual bar charts.',
  'Geometrical terms': 'No circle vocabulary (chord, arc, sector, segment, tangent) or triangle types.',
  'Ordering': 'Y7/Y8 level only.',
  'Algebraic fractions': 'Only one simplifying question; no adding, subtracting, multiplying or dividing.',
  'Drawing linear graphs': 'No lines in the form ax + by = c.',
  'Length and midpoint': 'Only in Add Maths; no Y10 version.',
  'Equations of linear graphs': 'No ax + by = c form.',
  'Graphs of functions': 'No tangent drawn to estimate a gradient.',
  'Circles, arcs and sectors': 'No reverse problems (find the angle or radius).',
  'Indices II': 'Nothing exists: algebraic negative and fractional indices.',
  'Surface area and volume': 'No volume of a pyramid.',
  'Cumulative frequency diagrams': 'No percentiles.',
  'Standard form': 'No adding or subtracting in standard form.',
  'Exact trigonometric values': 'Values listed but never used to find exact lengths or angles.',
  'Parallel lines': 'Only in Add Maths; no Y10 version.',
  'Perpendicular lines': 'Only in Add Maths; no Y10 version.',
  'Limits of accuracy': 'No calculations with bounds (max/min area, speed, division).',
  'Sets': 'No ⊆ or ⊂, no {x : …} notation, no shading like (A∪B)′.',
  "Pythagoras' theorem and trigonometry in 3D": 'Only the cuboid diagonal; nothing on pyramids or the angle between a line and a plane at Y10.',
  'Vector geometry': 'No collinearity proofs or general-ratio problems.',
  'Differentiation': 'No negative powers (e.g. 4/x²).',
  'Non-right-angled triangles (area of triangle, ambiguous case)': 'No ambiguous-case question.',
  "Pythagoras' theorem & trigonometry in 3D (angle between line and plane)": 'Only one Add Maths question.',
  'Vector geometry (ratio, collinearity, proof-style problems)': 'Nothing exists.',
};
